name: Telegram Notification
on: [push, pull_request]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ TG}}
        token: ${{ TG.6578656535:AAHgLYgctI1jXiBQK0KY1RhHbByoBie-j1g }}
        message: "GitHub Action Event Triggered!"
