name: Telegram Notification
on: [push, pull_request]
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Сообщение с GitHub о том, что мы смогли отправить сообщение в тг, подливая что-то в гитхаб!"
